# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild-delivery]
steps:
# [START Access the cloudbuild private key file from Secret Manager]
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=288264074061-cloudbuild_gserviceaccount_com > /root/.ssh/288264074061-cloudbuild_gserviceaccount_com' ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# [END Access the cloudbuild private key file from Secret Manager]

# [START Set up git with key and domain]
- name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    set -x
    chmod 600 /root/.ssh/288264074061-cloudbuild_gserviceaccount_com
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/288264074061-cloudbuild_gserviceaccount_com
    EOF
    mv known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# [END Set up git with key and domain]

# [START GKE deployment]
# This step deploys the new version of our container image
# in the hello-cloudbuild Kubernetes Engine cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'kubernetes.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'
# [END GKE deployment]

# [START Push to the github repository - Production branch]
# This step copies the applied manifest to the production branch
# The COMMIT_SHA variable is automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    set -x && \
    git clone --depth 1 --no-single-branch 'git@github.com:kenly-ldk/hello-cloudbuild-env.git' && \
    cd hello-cloudbuild-env && \
    git remote rename origin github && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git config user.name $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git checkout production && \
    git checkout $COMMIT_SHA kubernetes.yaml && \
    git commit -m "Manifest from commit $COMMIT_SHA $(git log --format=%B -n 1 $COMMIT_SHA)" && \
    git push github production
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# [END Push to the github repository - Production branch]
# [END cloudbuild-delivery]
